package account

import "errors"

var (
	ErrNotFound                    = errors.New("account not found")
	ErrTelegramUserIDTaken         = errors.New("telegram user ID is already assigned")
	ErrTelegramChatIDTaken         = errors.New("telegram chat ID is already assigned")
	ErrNilStorage                  = errors.New("account storage is nil")
	ErrInvalidDisplayName          = errors.New("display name is invalid")
	ErrInvalidMonthlyFee           = errors.New("monthly fee must be positive")
	ErrUnsupportedCurrency         = errors.New("currency is not supported")
	ErrInvalidAnchorDay            = errors.New("billing anchor day is invalid")
	ErrInvalidNextChargeOn         = errors.New("next charge date is invalid")
	ErrInvalidUserStatus           = errors.New("user status is invalid")
	ErrInvalidUserStatusTransition = errors.New("user status transition is invalid")
	ErrInvalidUserPageLimit        = errors.New("user page limit must be positive")
	ErrResumeDateRequired          = errors.New("resume requires a next charge date")
	ErrInvalidInviteTTL            = errors.New("invite TTL must be at least one second")
	ErrInvalidInviteToken          = errors.New("invite token is invalid")
	ErrInviteNotFound              = errors.New("invite token not found")
	ErrInviteExpired               = errors.New("invite token expired")
	ErrInviteAlreadyUsed           = errors.New("invite token already used")
	ErrInviteUserLinked            = errors.New("invite profile is already linked")
	ErrInviteTokenGenerate         = errors.New("failed to generate invite token")
	ErrInvalidLedgerAmount         = errors.New("ledger amount must be non-zero")
	ErrInvalidPaymentAmount        = errors.New("payment amount must be positive")
	ErrInvalidAdminTelegramID      = errors.New("admin Telegram ID must be positive")
	ErrAdjustmentNoteRequired      = errors.New("adjustment requires a note")
	ErrReversalNoteRequired        = errors.New("reversal requires a note")
	ErrLedgerEntryNotFound         = errors.New("ledger entry not found")
	ErrLedgerEntryAlreadyReversed  = errors.New("ledger entry already reversed")
	ErrReversalUserMismatch        = errors.New("ledger entry belongs to another user")
	ErrCannotReverseReversal       = errors.New("a reversal entry cannot be reversed")
)
